### ISSUE TITLE
python3 demo_render.py error 

### ISSUE THREAD

**Issue by luweishuang** [rwenqi/3Dfacedeblurring#1]
python3 demo_render.py and got the error "InvalidArgumentError (see above for traceback): RasterizeTriangles expects vertices to have shape (-1, 4)."

**Comment by lyp-deeplearning** [comment]
I have got the same error when i use my own picture in this program, i want to ask if the reason is about the picture we used?

**Comment by ilovecv** [comment]
I am able to run rasterize_triangles_kernel.so from this repo directly if I use python==3.5.6 and tensorflow-gpu==1.9.0.

**Comment by Jia-666** [comment]
> python3 demo_render.py并收到错误“ InvalidArgumentError（请参阅上面的回溯）：RasterizeTriangles期望顶点的形状为（-1，4）”。

Hi,I have the same problem.Have you solved it?Can you tell me how to deal with it?

**Comment by Jia-666** [comment]
> python3 demo_render.py and got the error "InvalidArgumentError (see above for traceback): RasterizeTriangles expects vertices to have shape (-1, 4)."

Hi,I have the same problem.Have you solved it?Can you tell me how to deal with it?

**Comment by yangjiaolong** [comment]
Hi all, the previous render_op.pb is not compatible with the new tf_mesh_renderer version. Now we have recompiled the pb file to resolve the issue (thanks to @YuDeng) and pls try the new one.

**Comment by 15458wew** [comment]
> Hi all, the previous render_op.pb is not compatible with the new tf_mesh_renderer version. Now we have recompiled the pb file to resolve the issue (thanks to @YuDeng) and pls try the new one.

Hello, where can I download the new pb file.
